openapi: 3.0.3
info:
  title: Service
  version: "0.0.0"
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      description: "Get Hello"
      responses:
        200:
          description: "Get Hello"
          content:
            text/plain:
              schema:
                type: "string"
