openapi: 3.0.3
info:
  title: Service
  version: "0.0.0"
servers:
  - url: http://localhost:3000
paths:
  /funds/credit:
    post:
      description: "Пополнение средств пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "123e4567-e89b-12d3-a456-426614174001"
                amount:
                  type: integer
                  example: 200
      responses:
        200:
          description: OK

  /funds/reserve:
    post:
      description: "Резервирование средств пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: '123e4567-e89b-12d3-a456-426614174001'
                serviceId:
                  type: string
                  example: '123e4567-e89b-12d3-a456-426614174001'
                orderId:
                  type: string
                  example: '123e4567-e89b-12d3-a456-426614174001'
                amount:
                  type: integer
                  example: 100
      responses:
        200:
          description: OK
  /funds/reserve/approve:
    post:
      description: "Подтверждение платежа"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  example: '123e4567-e89b-12d3-a456-426614174001'
      responses:
        200:
          description: OK
  /funds/{userId}:
    get:
      description: "Получение баланса пользователя"
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: '123e4567-e89b-12d3-a456-426614174001'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: integer
                    example: 100
